version: '1.0'
services:
  postgres:
    container_name: DataBase
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pbz_lr1
    ports:
      - '5432:5432'
    volumes:
      - ./p1.init.sql:/docker-entrypoint-initdb.d/p1.init.sql
      - ./p2.init.sql:/docker-entrypoint-initdb.d/p2.init.sql
      #- db-data:/var/lib/postgresql/data
      
volumes:
  db-data:
    name: db-data